<a href="https://colab.research.google.com/github/Okesha2000/Data-analysis-with-python-and-pandas/blob/main/Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## Array

In [147]:
import numpy as np

sales = [5, 3, 4, 9, 8, 10, 85, 45]

sales = np.array(sales)

print(f"Dimension: {sales.ndim}" )
print(f"Shape: {sales.shape}")
print(f"Size: {sales.size}")
print(f"Data type: {sales.dtype}")


Dimension: 1
Shape: (8,)
Size: 8
Data type: int64


In [148]:
array1 = np.array(range(5))
print(array1)

[0 1 2 3 4]


In [149]:
print(np.array(['I', 'Love', 'Python']))

['I' 'Love' 'Python']


## Two Dimensional Array

In [150]:
sales2 = [[1,2,3,4,5,6],
          [4,5,6,7,8,9],
          [7,8,9,1,2,3]]

sales2 = np.array(sales2)

print(f"Dimension: {sales2.ndim}" )
print(f"Shape: {sales2.shape}")
print(f"Size: {sales2.size}")
print(f"Data type: {sales2.dtype}")

Dimension: 2
Shape: (3, 6)
Size: 18
Data type: int64


In [151]:
array2d = np.array([range(5), range(5)])
print(array2d)
print(array2d.shape)

[[0 1 2 3 4]
 [0 1 2 3 4]]
(2, 5)


## Transforming array

In [152]:
transpose= array2d.T
print(transpose)
transpose.shape

[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]]


(5, 2)

## reshaping array

In [153]:
arrays = np.array(range(10))
print(arrays)

r1 = arrays.reshape(10,1)
print(r1)

r2 = arrays.reshape(2,5)
print(r2)

[0 1 2 3 4 5 6 7 8 9]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Creation Arrays

### Ones array

In [154]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [155]:
np.ones((2,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Zeros Array

In [156]:
np.zeros(100, dtype=int).reshape(5,20)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### Identity

In [157]:
np.identity(10).T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### arange

In [158]:
np.arange(20,step = 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### linspace

In [159]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [160]:
np.linspace(8,64,8)

array([ 8., 16., 24., 32., 40., 48., 56., 64.])

## Random Number Generation

In [161]:
from numpy.random import default_rng

In [162]:
rng = default_rng(12345)

ran_array = rng.random(10)
ran_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [163]:
mean, stdev = 5,1
nor_array = rng.normal(mean, stdev, 10)
print(nor_array)

[7.34740965 5.96849691 4.24061282 5.90219827 4.53304683 4.93931048
 5.78884434 3.74333187 5.57585751 6.39897899]


## Indexing and slicing

In [164]:
product = np.array(['fruit', 'vegetables', 'leaves', 'branches', 'trees', 'flowers'])

print(product[-1])



flowers


In [165]:
print(product[2])



leaves


In [166]:
print(product[:5])



['fruit' 'vegetables' 'leaves' 'branches' 'trees']


In [167]:
print(product[5::2])  # shows second element from back



['flowers']


In [168]:
print(product[2:5:2])



['leaves' 'trees']


In [169]:
product2d = product.reshape(3,2)
print(product2d)

print(product2d[1,1])



[['fruit' 'vegetables']
 ['leaves' 'branches']
 ['trees' 'flowers']]
branches


In [170]:
print(product2d[1:,:]) # show all rows from index 1 and all columns

[['leaves' 'branches']
 ['trees' 'flowers']]


## Arithmetic Operations for arrays

In [171]:
sales3 = [[1,2,3,4,5,6], [4,5,6,7,8,9]]

sales3 = np.array(sales3)
print(sales3)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [172]:
print(sales3+2
      )

[[ 3  4  5  6  7  8]
 [ 6  7  8  9 10 11]]


In [173]:
sales4 = np.arange(0,12).reshape(2,6)
print(sales4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### addition

In [174]:
sums = sales3+sales4
print(sums)

[[ 1  3  5  7  9 11]
 [10 12 14 16 18 20]]


### subtraction

In [175]:
subs = sales3- sales4
print(subs)

[[ 1  1  1  1  1  1]
 [-2 -2 -2 -2 -2 -2]]


In [176]:
m1 = np.arange(0,9).reshape(3,3)
m2 = np.arange(10,19).reshape(3,3)

print(m1)
print(m2)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


### product

In [177]:
mul = m1*m2
print(mul)

[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]


### array of integers

In [178]:
inventory = rng.integers(1,100,10)
print(inventory)

[71  9 39 16 74 34 47 47 48 27]


In [179]:
inventory - 12

array([59, -3, 27,  4, 62, 22, 35, 35, 36, 15])

In [180]:
(inventory/2).dtype

dtype('float64')

### Rounding

In [181]:
price = (rng.random(10)*10).round(2)
print(price)

[8.16 1.93 1.29 0.92 5.99 8.55 6.02 9.32 7.25 8.61]


In [182]:
(price * inventory).sum()

2697.1699999999996

### making array to list

In [183]:
lists = list(inventory)
lists

[71, 9, 39, 16, 74, 34, 47, 47, 48, 27]

### multiplying each element in two arrays

In [184]:
[x*y for x,y in zip(inventory, price)]

[579.36,
 17.37,
 50.31,
 14.72,
 443.26,
 290.70000000000005,
 282.94,
 438.04,
 348.0,
 232.46999999999997]

## operations for lists

m1

In [185]:
new_list= []

for x in lists:
  new_list.append(x+2)

new_list

[73, 11, 41, 18, 76, 36, 49, 49, 50, 29]

m2

In [186]:
[x+2 for x in lists]

[73, 11, 41, 18, 76, 36, 49, 49, 50, 29]

## Filter arrays

In [187]:
sales = np.array([[0, 5, 155, 206, 0],
                 [0, 1827, 616, 317, 325]])

sales

array([[   0,    5,  155,  206,    0],
       [   0, 1827,  616,  317,  325]])

In [188]:
sales != 0

array([[False,  True,  True,  True, False],
       [False,  True,  True,  True,  True]])

In [189]:
sales[sales != 0]

array([   5,  155,  206, 1827,  616,  317,  325])

In [190]:
sales[((sales == 616) | (sales < 100)) & (sales != 0)]

array([  5, 616])

In [191]:
sales[(sales > 10) & (sales <500)]

array([155, 206, 317, 325])

### extracting from one array with respect to the values from another array

In [192]:
product = np.array(['fruit', 'tree', 'leaves', 'branches', 'vegetables', 'flowers'])
new_sales = np.array([10,20,30,40,50,60])

product[(new_sales > 30)]

array(['branches', 'vegetables', 'flowers'], dtype='<U10')

## modifying array values

In [193]:
new_sales = np.array([10,20,30,40,50,60])
new_sales[2] = 25
new_sales

array([10, 20, 25, 40, 50, 60])

In [194]:
new_sales[2:] = [30,35,45,55]
new_sales

array([10, 20, 30, 35, 45, 55])

In [195]:
new_sales[new_sales == 20] = 52
new_sales

array([10, 52, 30, 35, 45, 55])

### even odd

In [196]:
myarray = np.arange(20)
myarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [197]:
odd_even = np.array(['even','odd']*10)
odd_even

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [198]:
myarray[odd_even == 'odd'] = 0
myarray

array([ 0,  0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,
        0, 18,  0])

## Where function

In [199]:
inventory_array = np.array([5,10,20,50,12,8])
np.where(inventory_array < 10, 'Out of stock', 'In stock')

array(['Out of stock', 'In stock', 'In stock', 'In stock', 'In stock',
       'Out of stock'], dtype='<U12')

In [200]:
product = np.array(['fruit', 'tree', 'leaves', 'branches', 'vegetables', 'flowers'])
np.where(inventory_array < 10, 'Out of stock', product)

array(['Out of stock', 'tree', 'leaves', 'branches', 'vegetables',
       'Out of stock'], dtype='<U12')

In [201]:
my = np.arange(0,20)
np.where(my % 2 ==0, 'even', np.where(my == 9, my, 'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U21')

# Array aggregation

In [202]:
sales = np.array([[0, 5, 155, 206, 0],
                 [0, 1827, 616, 317, 325]])

print(sales)

[[   0    5  155  206    0]
 [   0 1827  616  317  325]]


### Single value

In [203]:
sales.sum()

3451

In [204]:
sales.mean()

345.1

In [205]:
sales.max()

1827

In [206]:
sales.min()

0

### aggregation accross columns and rows

In [207]:
sales.sum(axis=0)       #aggregate accross rows

array([   0, 1832,  771,  523,  325])

In [208]:
sales.sum(axis=1)     # aggregate accross columns

array([ 366, 3085])

## Array functions

In [209]:
np.median(sales)

180.5

In [210]:
np.percentile(sales, 90)

737.0999999999996

In [211]:
np.unique(sales)

array([   0,    5,  155,  206,  317,  325,  616, 1827])

In [212]:
np.sqrt(sales)

array([[ 0.        ,  2.23606798, 12.4498996 , 14.35270009,  0.        ],
       [ 0.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

## Sorting arrays

In [213]:
product = [11.2, 2.56, 6.36, 12.25, 8.36, 25.12, 9.32, 5.47]


In [214]:
np.sort(product)

array([ 2.56,  5.47,  6.36,  8.36,  9.32, 11.2 , 12.25, 25.12])

In [215]:
product

[11.2, 2.56, 6.36, 12.25, 8.36, 25.12, 9.32, 5.47]

In [216]:
product.sort()
product

[2.56, 5.47, 6.36, 8.36, 9.32, 11.2, 12.25, 25.12]

In [217]:
product[-1]

25.12

In [218]:
product[::-1]

[25.12, 12.25, 11.2, 9.32, 8.36, 6.36, 5.47, 2.56]

## Broadcasting

In [219]:
testing = np.array([[1,2,3], [1,2,3], [1,2,3]])
testing

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [220]:
testing[0,:] + testing[:,1].reshape(1,3)

array([[3, 4, 5]])

# Pandas

In [221]:
import pandas as pd

## Series

In [222]:
sales = [0,20,30,40,50,65,85,96,102,25,45]

sales_series = pd.Series(sales, name='sales')
sales_series

0       0
1      20
2      30
3      40
4      50
5      65
6      85
7      96
8     102
9      25
10     45
Name: sales, dtype: int64

In [223]:
print(sales_series.values)
print(sales_series.values.mean())
print(sales_series.mean())

[  0  20  30  40  50  65  85  96 102  25  45]
50.72727272727273
50.72727272727273


In [224]:
print(sales_series.index)

sales_series.index = [10,20,30,40,50,60,70,80,90,100,110]

print(sales_series)

RangeIndex(start=0, stop=11, step=1)
10       0
20      20
30      30
40      40
50      50
60      65
70      85
80      96
90     102
100     25
110     45
Name: sales, dtype: int64


In [225]:
sales_series.name

'sales'

In [226]:
sales_series.dtype

dtype('int64')

In [227]:
pd.Series(np.arange(5))

0    0
1    1
2    2
3    3
4    4
dtype: int64

## Type conversion

In [228]:
sales_series.astype('bool')

10     False
20      True
30      True
40      True
50      True
60      True
70      True
80      True
90      True
100     True
110     True
Name: sales, dtype: bool

In [229]:
sales_series.astype('int64')

10       0
20      20
30      30
40      40
50      50
60      65
70      85
80      96
90     102
100     25
110     45
Name: sales, dtype: int64

In [230]:
sales_series.astype('float64')

10       0.0
20      20.0
30      30.0
40      40.0
50      50.0
60      65.0
70      85.0
80      96.0
90     102.0
100     25.0
110     45.0
Name: sales, dtype: float64

In [231]:
pd.Series(np.arange(5)).astype('object')

0    0
1    1
2    2
3    3
4    4
dtype: object

## Index of series

### Diff between array and series in terms of indexes

In [232]:
sales = [0,5,155,0,518]
items = ['coffee', 'bananas', 'tea', 'coconut', 'sugar']

sales_array = np.array(sales)
items_array = np.array(items)

sales_series = pd.Series(sales, index=items, name='sales series')
sales_series

coffee       0
bananas      5
tea        155
coconut      0
sugar      518
Name: sales series, dtype: int64

In [233]:
sales_series['sugar']

518

In [234]:
sales_array[items_array=='sugar']

array([518])

In [235]:
sales_series['bananas':'coconut']


bananas      5
tea        155
coconut      0
Name: sales series, dtype: int64

In [236]:
sales_array[2:5]

array([155,   0, 518])

### index use in series

In [237]:
my_series = pd.Series(range(5))
my_series

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [238]:
my_series[3]

3

In [239]:
my_series[1:3]

1    1
2    2
dtype: int64

In [240]:
my_series[1::3]

1    1
4    4
dtype: int64

In [241]:
my_series = pd.Series(range(5), index =('Day0', 'Day1', 'Day2', 'Day3', 'Day4'))
my_series

Day0    0
Day1    1
Day2    2
Day3    3
Day4    4
dtype: int64

In [242]:
my_series['Day2']

2

In [243]:
my_series['Day1':'Day3']

Day1    1
Day2    2
Day3    3
dtype: int64

In [244]:
my_series[::2] # every other values in 2

Day0    0
Day2    2
Day4    4
dtype: int64

## .iloc

In [245]:
sales = [0,5,155,0,518]
items = ['coffee', 'bananas', 'tea', 'coconut', 'sugar']

sales_series = pd.Series(sales, index= items, name= 'sales series')
sales_series

coffee       0
bananas      5
tea        155
coconut      0
sugar      518
Name: sales series, dtype: int64

In [246]:
sales_series.iloc[2]

155

In [247]:
sales_series.iloc[2:5]

tea        155
coconut      0
sugar      518
Name: sales series, dtype: int64

In [248]:
sales_series.iloc[[1,2,4]]

bananas      5
tea        155
sugar      518
Name: sales series, dtype: int64

## .loc

In [249]:
my_series = pd.Series(range(5), index =('Day0', 'Day1', 'Day2', 'Day3', 'Day4'))
my_series

Day0    0
Day1    1
Day2    2
Day3    3
Day4    4
dtype: int64

In [250]:
my_series.loc['Day2']

2

In [251]:
my_series.loc[['Day2', 'Day4']]

Day2    2
Day4    4
dtype: int64

In [252]:
my_series.loc['Day2':'Day4']

Day2    2
Day3    3
Day4    4
dtype: int64

In [253]:
my_series.index = [0,2,3,100,5]
my_series

0      0
2      1
3      2
100    3
5      4
dtype: int64

In [254]:
my_series.loc[0:3]

0    0
2    1
3    2
dtype: int64

In [255]:
my_series.loc[3:5]

3      2
100    3
5      4
dtype: int64

In [256]:
my_series.reset_index(drop=True)

0    0
1    1
2    2
3    3
4    4
dtype: int64

## Duplicate index values

In [257]:
sales = [0,5,155,0,518]
items = ['coffee', 'coffee', 'tea', 'coconut', 'sugar']

sales_series = pd.Series(sales, name ='sales series', index = items)
sales_series

coffee       0
coffee       5
tea        155
coconut      0
sugar      518
Name: sales series, dtype: int64

In [258]:
sales_series.loc['coffee']

coffee    0
coffee    5
Name: sales series, dtype: int64

In [259]:
sales_series.reset_index()

index  sales series
0   coffee             0
1   coffee             5
2      tea           155
3  coconut             0
4    sugar           518

## Filtering series & Logical operations

In [260]:
sales = [0,5,155,0,518]
items = ['coffee', 'banana', 'tea', 'coconut', 'sugar']

sales_series = pd.Series(sales, name ='sales series', index = items)
sales_series

coffee       0
banana       5
tea        155
coconut      0
sugar      518
Name: sales series, dtype: int64

In [261]:
sales_series.loc[sales_series > 0]

banana      5
tea       155
sugar     518
Name: sales series, dtype: int64

In [262]:
mask = (sales_series > 0) & (sales_series.index == 'banana')
sales_series[mask]

banana    5
Name: sales series, dtype: int64

In [263]:
sales_series.loc[-(sales_series==5)]

coffee       0
tea        155
coconut      0
sugar      518
Name: sales series, dtype: int64

In [264]:
sales_series[sales_series.isin([0, 518])]

coffee       0
coconut      0
sugar      518
Name: sales series, dtype: int64

In [265]:
sales_series.loc[~sales_series.isin([0, 518])]

banana      5
tea       155
Name: sales series, dtype: int64

In [266]:
sales_series.loc[-(sales_series>100)]

coffee     0
banana     5
coconut    0
Name: sales series, dtype: int64

## sorting

In [267]:
sales_series.sort_values()

coffee       0
coconut      0
banana       5
tea        155
sugar      518
Name: sales series, dtype: int64

In [268]:
sales_series.sort_values(ascending=False)

sugar      518
tea        155
banana       5
coffee       0
coconut      0
Name: sales series, dtype: int64

In [269]:
sales_series.sort_index()

banana       5
coconut      0
coffee       0
sugar      518
tea        155
Name: sales series, dtype: int64

## Arithmetic operations

In [270]:
monday_sales = pd.Series([2,5,3,9,10,12])
monday_sales

0     2
1     5
2     3
3     9
4    10
5    12
dtype: int64

In [271]:
monday_sales + 2

0     4
1     7
2     5
3    11
4    12
5    14
dtype: int64

In [272]:
monday_sales.add(2)

0     4
1     7
2     5
3    11
4    12
5    14
dtype: int64

In [273]:
price = '$'+monday_sales.add(0, fill_value=0).astype('float').astype('string')
price

0     $2.0
1     $5.0
2     $3.0
3     $9.0
4    $10.0
5    $12.0
dtype: string

In [274]:
monday_sales = pd.Series([2,np.NaN,3,9,10,12])
monday_sales.add(2, fill_value=0) # if you see a missing value you will fill that with 0


0     4.0
1     2.0
2     5.0
3    11.0
4    12.0
5    14.0
dtype: float64

In [275]:
monday_sales/2

0    1.0
1    NaN
2    1.5
3    4.5
4    5.0
5    6.0
dtype: float64

In [276]:
monday_sales // 2

0    1.0
1    NaN
2    1.0
3    4.0
4    5.0
5    6.0
dtype: float64

## String Methods

In [277]:
price

0     $2.0
1     $5.0
2     $3.0
3     $9.0
4    $10.0
5    $12.0
dtype: string

In [278]:
price[price.str.contains('3')]

2    $3.0
dtype: string

In [279]:
clean = price.str.strip('$').astype('float')
clean

0     2.0
1     5.0
2     3.0
3     9.0
4    10.0
5    12.0
dtype: float64

In [280]:
my_series = pd.Series(['Day0', 'Day1', 'Day2', 'Day3', 'Day4'])
my_series

0    Day0
1    Day1
2    Day2
3    Day3
4    Day4
dtype: object

In [281]:
my_series.str[-1]

0    0
1    1
2    2
3    3
4    4
dtype: object

In [282]:
my_series.str.upper()

0    DAY0
1    DAY1
2    DAY2
3    DAY3
4    DAY4
dtype: object

In [283]:
splitted = my_series.str.replace("Day", "Day ")
splitted

0    Day 0
1    Day 1
2    Day 2
3    Day 3
4    Day 4
dtype: object

In [284]:
splitted.str.split(" ", expand=True)

0  1
0  Day  0
1  Day  1
2  Day  2
3  Day  3
4  Day  4

In [285]:
splitted.str.len()

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [286]:
splitted.str[0:2]

0    Da
1    Da
2    Da
3    Da
4    Da
dtype: object

## Numerical Series aggregation

In [287]:
sales = [0,5,155,0,518]
items = ['coffee', 'coffee', 'tea', 'coconut', 'sugar']

sales_series = pd.Series(sales, index=items, name='sales series')
sales_series

coffee       0
coffee       5
tea        155
coconut      0
sugar      518
Name: sales series, dtype: int64

In [288]:
sales_series.sum()

678

In [289]:
sales_series.loc['coffee'].sum()

5

In [290]:
sales_series.quantile([0.25,0.75,0.9])

0.25      0.0
0.75    155.0
0.90    372.8
Name: sales series, dtype: float64

In [291]:
transaction = pd.read_csv('/content/transactions.csv')
transaction_series = pd.Series(transaction['transactions'], name='transactions')
transaction_series

0         770
1        2111
2        2358
3        3487
4        1922
         ... 
83483    2804
83484    1573
83485    2255
83486     932
83487     802
Name: transactions, Length: 83488, dtype: int64

In [292]:
transaction_series.iloc[:5]

0     770
1    2111
2    2358
3    3487
4    1922
Name: transactions, dtype: int64

In [293]:
transaction_series.count()

83488

In [294]:
transaction_series.sum()

141478945

In [295]:
transaction_series.iloc[:5].quantile([0.4],interpolation='nearest')   # nearest number is shown for the 0.4th percentile

0.4    2111
Name: transactions, dtype: int64

## Categorical series aggregation

In [296]:
items = ['coffee', 'coffee', 'tea', 'coconut', 'sugar']

item_series = pd.Series(items, name='item series')
item_series

0     coffee
1     coffee
2        tea
3    coconut
4      sugar
Name: item series, dtype: object

In [297]:
item_series.unique()

array(['coffee', 'tea', 'coconut', 'sugar'], dtype=object)

In [298]:
item_series.nunique()

4

In [299]:
item_series.value_counts(normalize=True)

item series
coffee     0.4
tea        0.2
coconut    0.2
sugar      0.2
Name: proportion, dtype: float64

## Missing Values

In [300]:
sales = [0,5,155,pd.NA,518]

items = ['coffee', 'coffee', 'tea', 'coconut', 'sugar']

sales_series = pd.Series(sales, index=items, name='sales series')
sales_series

coffee        0
coffee        5
tea         155
coconut    <NA>
sugar       518
Name: sales series, dtype: object

# find missing values

In [301]:
sales_series.isna()

coffee     False
coffee     False
tea        False
coconut     True
sugar      False
Name: sales series, dtype: bool

In [302]:
sales_series.value_counts(dropna=False)

sales series
0       1
5       1
155     1
<NA>    1
518     1
Name: count, dtype: int64

### remove

In [303]:
sales_series.dropna()

coffee      0
coffee      5
tea       155
sugar     518
Name: sales series, dtype: object

### replace with zero

In [304]:
sales_series.fillna(0)

<ipython-input-304-0b51ded494d6>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  sales_series.fillna(0)


coffee       0
coffee       5
tea        155
coconut      0
sugar      518
Name: sales series, dtype: int64

### impute with mean

In [305]:
sales_series.fillna(sales_series.mean())

<ipython-input-305-17398c081aad>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  sales_series.fillna(sales_series.mean())


coffee       0.0
coffee       5.0
tea        155.0
coconut    169.5
sugar      518.0
Name: sales series, dtype: float64

## Apply function

In [306]:
def discount(price):
  if price>20:
    return round(price*0.9,2)
  return(price)


clean_wholesale = pd.Series([3.99,5.99,22.99,7.99,33.99])
clean_wholesale

0     3.99
1     5.99
2    22.99
3     7.99
4    33.99
dtype: float64

In [307]:
clean_wholesale.apply(discount)

0     3.99
1     5.99
2    20.69
3     7.99
4    30.59
dtype: float64

In [308]:
clean_wholesale.apply(lambda x: round(x*0.9,2) if x>20 else x)

0     3.99
1     5.99
2    20.69
3     7.99
4    30.59
dtype: float64

In [309]:
string_series = pd.Series(['Day0', 'Day0', 'Day1', 'Day1', 'Day2'])
string_series

0    Day0
1    Day0
2    Day1
3    Day1
4    Day2
dtype: object

In [310]:
string_series.apply(lambda x: x[-1])

0    0
1    0
2    1
3    1
4    2
dtype: object

In [311]:
def search (string, looking_for):
  if looking_for in string:
    return 'Found it!'
  return 'Nope'

In [312]:
string_series.apply(search, args='2')

0         Nope
1         Nope
2         Nope
3         Nope
4    Found it!
dtype: object

## .where function

In [313]:
clean_wholesale = pd.Series([3.99,5.99,22.99,7.99,33.99])
clean_wholesale

0     3.99
1     5.99
2    22.99
3     7.99
4    33.99
dtype: float64

In [314]:
clean_wholesale.where(clean_wholesale<=20, round(clean_wholesale*0.9,2))

0     3.99
1     5.99
2    20.69
3     7.99
4    30.59
dtype: float64

In [315]:
string_series = pd.Series(['Day0', 'Day0', 'Day1', 'Day1', 'Day2'])
string_series

0    Day0
1    Day0
2    Day1
3    Day1
4    Day2
dtype: object

In [316]:
string_series.where(string_series.str.contains('2'), 'nope').where(~string_series.str.contains('2'), 'Found')

0     nope
1     nope
2     nope
3     nope
4    Found
dtype: object

# Data frame

In [317]:
df = pd.DataFrame({'id': [1,2],
                  'Str_no' : [1,2],
                  'Family' : ['Poultry', 'Produce']})

df

id  Str_no   Family
0   1       1  Poultry
1   2       2  Produce

In [318]:
oil = pd.read_csv('/content/oil.csv')
oil

date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [319]:
oil.shape

(1218, 2)

In [320]:
oil.size

2436

In [321]:
oil.columns

Index(['date', 'dcoilwtico'], dtype='object')

In [322]:
oil.columns = ['Date', 'Price']
oil

Date  Price
0     2013-01-01    NaN
1     2013-01-02  93.14
2     2013-01-03  92.97
3     2013-01-04  93.12
4     2013-01-07  93.20
...          ...    ...
1213  2017-08-25  47.65
1214  2017-08-28  46.40
1215  2017-08-29  46.46
1216  2017-08-30  45.96
1217  2017-08-31  47.26

[1218 rows x 2 columns]

In [323]:
oil.index

RangeIndex(start=0, stop=1218, step=1)

In [324]:
oil.axes

[RangeIndex(start=0, stop=1218, step=1),
 Index(['Date', 'Price'], dtype='object')]

In [325]:
oil.dtypes

Date      object
Price    float64
dtype: object

## Exploring data frames

In [326]:
retail = pd.read_csv('/content/retail_2016_2017.csv')
retail

id        date  store_nbr       family   sales  onpromotion
0      1945944  2016-01-01        1.0   AUTOMOTIVE     0.0          0.0
1      1945945  2016-01-01        1.0    BABY CARE     0.0          0.0
2      1945946  2016-01-01        1.0       BEAUTY     0.0          0.0
3      1945947  2016-01-01        1.0    BEVERAGES     0.0          0.0
4      1945948  2016-01-01        1.0        BOOKS     0.0          0.0
...        ...         ...        ...          ...     ...          ...
51024  1996968  2016-01-29       40.0  CELEBRATION    95.0          0.0
51025  1996969  2016-01-29       40.0     CLEANING  1344.0          0.0
51026  1996970  2016-01-29       40.0        DAIRY   394.0          0.0
51027  1996971  2016-01-29       40.0         DELI   347.0         58.0
51028  1996972     2016-01        NaN          NaN     NaN          NaN

[51029 rows x 6 columns]

In [327]:
retail.head()

id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01        1.0  AUTOMOTIVE    0.0          0.0
1  1945945  2016-01-01        1.0   BABY CARE    0.0          0.0
2  1945946  2016-01-01        1.0      BEAUTY    0.0          0.0
3  1945947  2016-01-01        1.0   BEVERAGES    0.0          0.0
4  1945948  2016-01-01        1.0       BOOKS    0.0          0.0

In [328]:
retail.tail(3)

id        date  store_nbr family  sales  onpromotion
51026  1996970  2016-01-29       40.0  DAIRY  394.0          0.0
51027  1996971  2016-01-29       40.0   DELI  347.0         58.0
51028  1996972     2016-01        NaN    NaN    NaN          NaN

In [329]:
retail.sample(15)

id        date  store_nbr              family       sales  \
24524  1970468  2016-01-14       47.0        BREAD/BAKERY   759.65700   
23239  1969183  2016-01-14       11.0            CLEANING  1511.00000   
10522  1956466  2016-01-06       53.0             POULTRY   154.11101   
29908  1975852  2016-01-17       48.0                EGGS   278.00000   
9028   1954972  2016-01-06       12.0          LADIESWEAR     0.00000   
34956  1980900  2016-01-20        4.0                DELI   190.46400   
5216   1951160  2016-01-03        6.0              BEAUTY    24.00000   
27961  1973905  2016-01-16       43.0                EGGS    78.00000   
39520  1985464  2016-01-23       18.0          LADIESWEAR     5.00000   
17204  1963148  2016-01-10       41.0        FROZEN FOODS   179.84800   
27907  1973851  2016-01-16       41.0    LIQUOR,WINE,BEER   252.00000   
43694  1989638  2016-01-25       35.0              BEAUTY     0.00000   
50373  1996317  2016-01-29       22.0  HOME AND KITCHEN I    13.00000   
8759   1954703  2016-01-05       54.0            HARDWARE     0.00000   
31753  1977697  2016-01-18        5.0            CLEANING  1013.00000   

       onpromotion  
24524          2.0  
23239          0.0  
10522          1.0  
29908          0.0  
9028           0.0  
34956          0.0  
5216           1.0  
27961          0.0  
39520          0.0  
17204          0.0  
27907          0.0  
43694          0.0  
50373          0.0  
8759           0.0  
31753          6.0

In [330]:
retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51029 entries, 0 to 51028
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           51029 non-null  int64  
 1   date         51029 non-null  object 
 2   store_nbr    51028 non-null  float64
 3   family       51028 non-null  object 
 4   sales        51028 non-null  float64
 5   onpromotion  51028 non-null  float64
dtypes: float64(3), int64(1), object(2)
memory usage: 2.3+ MB


In [331]:
retail.info(show_counts=True) # to show Non-Null counts as numbers when you have large amount of data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51029 entries, 0 to 51028
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           51029 non-null  int64  
 1   date         51029 non-null  object 
 2   store_nbr    51028 non-null  float64
 3   family       51028 non-null  object 
 4   sales        51028 non-null  float64
 5   onpromotion  51028 non-null  float64
dtypes: float64(3), int64(1), object(2)
memory usage: 2.3+ MB


In [332]:
retail.describe()

id     store_nbr         sales   onpromotion
count  5.102900e+04  51028.000000  51028.000000  51028.000000
mean   1.971458e+06     27.379576    422.960225      2.134338
std    1.473095e+04     15.517627   1231.343845     12.085994
min    1.945944e+06      1.000000      0.000000      0.000000
25%    1.958701e+06     14.000000      1.000000      0.000000
50%    1.971458e+06     27.000000     18.000000      0.000000
75%    1.984215e+06     41.000000    238.735500      0.000000
max    1.996972e+06     54.000000  19988.629000    233.000000

In [333]:
retail.describe(include='all').round()

id        date  store_nbr      family    sales  onpromotion
count     51029.0       51029    51028.0       51028  51028.0      51028.0
unique        NaN          30        NaN          33      NaN          NaN
top           NaN  2016-01-01        NaN  AUTOMOTIVE      NaN          NaN
freq          NaN        1782        NaN        1547      NaN          NaN
mean    1971458.0         NaN       27.0         NaN    423.0          2.0
std       14731.0         NaN       16.0         NaN   1231.0         12.0
min     1945944.0         NaN        1.0         NaN      0.0          0.0
25%     1958701.0         NaN       14.0         NaN      1.0          0.0
50%     1971458.0         NaN       27.0         NaN     18.0          0.0
75%     1984215.0         NaN       41.0         NaN    239.0          0.0
max     1996972.0         NaN       54.0         NaN  19989.0        233.0

In [334]:
trans = pd.read_csv('/content/transactions.csv')
trans

date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [335]:
trans.head()

date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [336]:
trans.tail()

date  store_nbr  transactions
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

In [337]:
trans.sample(10)

date  store_nbr  transactions
54293  2016-02-08         50          2334
57395  2016-04-07         27          1324
17028  2014-01-04         30           746
41697  2015-06-07         32           703
35689  2015-02-05         11          2392
67606  2016-10-19         30           663
9600   2013-07-28         25           668
59130  2016-05-10         13           864
73561  2017-02-11         50          3172
17511  2014-01-14         44          3560

In [338]:
trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64 
 2   transactions  83488 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 1.9+ MB


since RangeIndex = Non-Null count there are no missing values.

In [339]:
trans.describe(include="all")

date     store_nbr  transactions
count        83488  83488.000000  83488.000000
unique        1682           NaN           NaN
top     2017-08-15           NaN           NaN
freq            54           NaN           NaN
mean           NaN     26.939237   1694.602158
std            NaN     15.608204    963.286644
min            NaN      1.000000      5.000000
25%            NaN     13.000000   1046.000000
50%            NaN     27.000000   1393.000000
75%            NaN     40.000000   2079.000000
max            NaN     54.000000   8359.000000

we have 1682 unique date counts

In [340]:
trans.isna().sum()

date            0
store_nbr       0
transactions    0
dtype: int64

## Access data frame columns

### m1

In [341]:
retail['family']

0         AUTOMOTIVE
1          BABY CARE
2             BEAUTY
3          BEVERAGES
4              BOOKS
            ...     
51024    CELEBRATION
51025       CLEANING
51026          DAIRY
51027           DELI
51028            NaN
Name: family, Length: 51029, dtype: object

### m2

In [342]:
retail.family

0         AUTOMOTIVE
1          BABY CARE
2             BEAUTY
3          BEVERAGES
4              BOOKS
            ...     
51024    CELEBRATION
51025       CLEANING
51026          DAIRY
51027           DELI
51028            NaN
Name: family, Length: 51029, dtype: object

## select multiple columns

In [343]:
retail[['family', 'store_nbr']]

family  store_nbr
0       AUTOMOTIVE        1.0
1        BABY CARE        1.0
2           BEAUTY        1.0
3        BEVERAGES        1.0
4            BOOKS        1.0
...            ...        ...
51024  CELEBRATION       40.0
51025     CLEANING       40.0
51026        DAIRY       40.0
51027         DELI       40.0
51028          NaN        NaN

[51029 rows x 2 columns]

## .iloc & .loc

### selecting rows

In [344]:
retail.iloc[:5,:]

id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01        1.0  AUTOMOTIVE    0.0          0.0
1  1945945  2016-01-01        1.0   BABY CARE    0.0          0.0
2  1945946  2016-01-01        1.0      BEAUTY    0.0          0.0
3  1945947  2016-01-01        1.0   BEVERAGES    0.0          0.0
4  1945948  2016-01-01        1.0       BOOKS    0.0          0.0

### selecting columns

In [345]:
retail.iloc[:, -2:]

sales  onpromotion
0         0.0          0.0
1         0.0          0.0
2         0.0          0.0
3         0.0          0.0
4         0.0          0.0
...       ...          ...
51024    95.0          0.0
51025  1344.0          0.0
51026   394.0          0.0
51027   347.0         58.0
51028     NaN          NaN

[51029 rows x 2 columns]

In [346]:
retail.iloc[:,:3]

id        date  store_nbr
0      1945944  2016-01-01        1.0
1      1945945  2016-01-01        1.0
2      1945946  2016-01-01        1.0
3      1945947  2016-01-01        1.0
4      1945948  2016-01-01        1.0
...        ...         ...        ...
51024  1996968  2016-01-29       40.0
51025  1996969  2016-01-29       40.0
51026  1996970  2016-01-29       40.0
51027  1996971  2016-01-29       40.0
51028  1996972     2016-01        NaN

[51029 rows x 3 columns]

### both rows and columns

In [347]:
retail.iloc[:5, 1:3]

date  store_nbr
0  2016-01-01        1.0
1  2016-01-01        1.0
2  2016-01-01        1.0
3  2016-01-01        1.0
4  2016-01-01        1.0

### selecting by label(loc)


In [348]:
retail.loc[:,['family', 'sales']]

family   sales
0       AUTOMOTIVE     0.0
1        BABY CARE     0.0
2           BEAUTY     0.0
3        BEVERAGES     0.0
4            BOOKS     0.0
...            ...     ...
51024  CELEBRATION    95.0
51025     CLEANING  1344.0
51026        DAIRY   394.0
51027         DELI   347.0
51028          NaN     NaN

[51029 rows x 2 columns]

### creating new columns

In [349]:
retail['new_sales'] = retail['sales']+2
retail

id        date  store_nbr       family   sales  onpromotion  \
0      1945944  2016-01-01        1.0   AUTOMOTIVE     0.0          0.0   
1      1945945  2016-01-01        1.0    BABY CARE     0.0          0.0   
2      1945946  2016-01-01        1.0       BEAUTY     0.0          0.0   
3      1945947  2016-01-01        1.0    BEVERAGES     0.0          0.0   
4      1945948  2016-01-01        1.0        BOOKS     0.0          0.0   
...        ...         ...        ...          ...     ...          ...   
51024  1996968  2016-01-29       40.0  CELEBRATION    95.0          0.0   
51025  1996969  2016-01-29       40.0     CLEANING  1344.0          0.0   
51026  1996970  2016-01-29       40.0        DAIRY   394.0          0.0   
51027  1996971  2016-01-29       40.0         DELI   347.0         58.0   
51028  1996972     2016-01        NaN          NaN     NaN          NaN   

       new_sales  
0            2.0  
1            2.0  
2            2.0  
3            2.0  
4            2.0  
...          ...  
51024       97.0  
51025     1346.0  
51026      396.0  
51027      349.0  
51028        NaN  

[51029 rows x 7 columns]

## Drop rows and columns

In [350]:
retail

id        date  store_nbr       family   sales  onpromotion  \
0      1945944  2016-01-01        1.0   AUTOMOTIVE     0.0          0.0   
1      1945945  2016-01-01        1.0    BABY CARE     0.0          0.0   
2      1945946  2016-01-01        1.0       BEAUTY     0.0          0.0   
3      1945947  2016-01-01        1.0    BEVERAGES     0.0          0.0   
4      1945948  2016-01-01        1.0        BOOKS     0.0          0.0   
...        ...         ...        ...          ...     ...          ...   
51024  1996968  2016-01-29       40.0  CELEBRATION    95.0          0.0   
51025  1996969  2016-01-29       40.0     CLEANING  1344.0          0.0   
51026  1996970  2016-01-29       40.0        DAIRY   394.0          0.0   
51027  1996971  2016-01-29       40.0         DELI   347.0         58.0   
51028  1996972     2016-01        NaN          NaN     NaN          NaN   

       new_sales  
0            2.0  
1            2.0  
2            2.0  
3            2.0  
4            2.0  
...          ...  
51024       97.0  
51025     1346.0  
51026      396.0  
51027      349.0  
51028        NaN  

[51029 rows x 7 columns]

In [351]:
retail.drop('new_sales',axis=1)

id        date  store_nbr       family   sales  onpromotion
0      1945944  2016-01-01        1.0   AUTOMOTIVE     0.0          0.0
1      1945945  2016-01-01        1.0    BABY CARE     0.0          0.0
2      1945946  2016-01-01        1.0       BEAUTY     0.0          0.0
3      1945947  2016-01-01        1.0    BEVERAGES     0.0          0.0
4      1945948  2016-01-01        1.0        BOOKS     0.0          0.0
...        ...         ...        ...          ...     ...          ...
51024  1996968  2016-01-29       40.0  CELEBRATION    95.0          0.0
51025  1996969  2016-01-29       40.0     CLEANING  1344.0          0.0
51026  1996970  2016-01-29       40.0        DAIRY   394.0          0.0
51027  1996971  2016-01-29       40.0         DELI   347.0         58.0
51028  1996972     2016-01        NaN          NaN     NaN          NaN

[51029 rows x 6 columns]

In [352]:
retail

id        date  store_nbr       family   sales  onpromotion  \
0      1945944  2016-01-01        1.0   AUTOMOTIVE     0.0          0.0   
1      1945945  2016-01-01        1.0    BABY CARE     0.0          0.0   
2      1945946  2016-01-01        1.0       BEAUTY     0.0          0.0   
3      1945947  2016-01-01        1.0    BEVERAGES     0.0          0.0   
4      1945948  2016-01-01        1.0        BOOKS     0.0          0.0   
...        ...         ...        ...          ...     ...          ...   
51024  1996968  2016-01-29       40.0  CELEBRATION    95.0          0.0   
51025  1996969  2016-01-29       40.0     CLEANING  1344.0          0.0   
51026  1996970  2016-01-29       40.0        DAIRY   394.0          0.0   
51027  1996971  2016-01-29       40.0         DELI   347.0         58.0   
51028  1996972     2016-01        NaN          NaN     NaN          NaN   

       new_sales  
0            2.0  
1            2.0  
2            2.0  
3            2.0  
4            2.0  
...          ...  
51024       97.0  
51025     1346.0  
51026      396.0  
51027      349.0  
51028        NaN  

[51029 rows x 7 columns]

In [353]:
retail.drop('id', axis=1, inplace=True)
retail

date  store_nbr       family   sales  onpromotion  new_sales
0      2016-01-01        1.0   AUTOMOTIVE     0.0          0.0        2.0
1      2016-01-01        1.0    BABY CARE     0.0          0.0        2.0
2      2016-01-01        1.0       BEAUTY     0.0          0.0        2.0
3      2016-01-01        1.0    BEVERAGES     0.0          0.0        2.0
4      2016-01-01        1.0        BOOKS     0.0          0.0        2.0
...           ...        ...          ...     ...          ...        ...
51024  2016-01-29       40.0  CELEBRATION    95.0          0.0       97.0
51025  2016-01-29       40.0     CLEANING  1344.0          0.0     1346.0
51026  2016-01-29       40.0        DAIRY   394.0          0.0      396.0
51027  2016-01-29       40.0         DELI   347.0         58.0      349.0
51028     2016-01        NaN          NaN     NaN          NaN        NaN

[51029 rows x 6 columns]

In [354]:
retail.drop(0, axis =0)

date  store_nbr        family   sales  onpromotion  new_sales
1      2016-01-01        1.0     BABY CARE     0.0          0.0        2.0
2      2016-01-01        1.0        BEAUTY     0.0          0.0        2.0
3      2016-01-01        1.0     BEVERAGES     0.0          0.0        2.0
4      2016-01-01        1.0         BOOKS     0.0          0.0        2.0
5      2016-01-01        1.0  BREAD/BAKERY     0.0          0.0        2.0
...           ...        ...           ...     ...          ...        ...
51024  2016-01-29       40.0   CELEBRATION    95.0          0.0       97.0
51025  2016-01-29       40.0      CLEANING  1344.0          0.0     1346.0
51026  2016-01-29       40.0         DAIRY   394.0          0.0      396.0
51027  2016-01-29       40.0          DELI   347.0         58.0      349.0
51028     2016-01        NaN           NaN     NaN          NaN        NaN

[51028 rows x 6 columns]

## Identifying and dropping duplicates

In [355]:
product_df = pd.DataFrame({'Product': ['Diary', 'Diary', 'Diary', 'Vegetables', 'Fruits'],
                           'Price' : [2.56, 2.56, 4.55, 2.74, 5.44]})

product_df

Product  Price
0       Diary   2.56
1       Diary   2.56
2       Diary   4.55
3  Vegetables   2.74
4      Fruits   5.44

In [356]:
product_df.shape

(5, 2)

In [357]:
product_df.nunique()

Product    3
Price      4
dtype: int64

In [358]:
product_df.duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [359]:
product_df.duplicated(subset='Product')

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [360]:
product_df.drop_duplicates(subset = 'Product', keep ='last', ignore_index=True)

Product  Price
0       Diary   4.55
1  Vegetables   2.74
2      Fruits   5.44

## Missing values


In [361]:
product_df = pd.DataFrame({'Product': [pd.NA, 'Diary', 'Diary', pd.NA, 'Fruits'],
                           'Price' : [2.56, pd.NA, 4.55, 2.74, pd.NA]})

product_df

Product Price
0    <NA>  2.56
1   Diary  <NA>
2   Diary  4.55
3    <NA>  2.74
4  Fruits  <NA>

In [362]:
product_df.isna().sum()

Product    2
Price      2
dtype: int64

In [363]:
product_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Product  3 non-null      object
 1   Price    3 non-null      object
dtypes: object(2)
memory usage: 208.0+ bytes


In [364]:
product_df.fillna(0)

<ipython-input-364-22d27beb2ded>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  product_df.fillna(0)


Product  Price
0       0   2.56
1   Diary   0.00
2   Diary   4.55
3       0   2.74
4  Fruits   0.00

In [365]:
product_df.dropna()

Product Price
2   Diary  4.55

In [366]:
product_df.fillna({'Price': 0})

<ipython-input-366-7afd67866231>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  product_df.fillna({'Price': 0})


Product  Price
0    <NA>   2.56
1   Diary   0.00
2   Diary   4.55
3    <NA>   2.74
4  Fruits   0.00

In [367]:
product_df.dropna(subset='Product')

Product Price
1   Diary  <NA>
2   Diary  4.55
4  Fruits  <NA>

## Filtering data frames

In [368]:
retail = pd.read_csv('/content/retail_2016_2017.csv')
retail.loc[retail['date'] == '2016-01-02']

id        date  store_nbr                      family       sales  \
1782  1947726  2016-01-02          1                  AUTOMOTIVE     7.00000   
1783  1947727  2016-01-02          1                   BABY CARE     0.00000   
1784  1947728  2016-01-02          1                      BEAUTY     0.00000   
1785  1947729  2016-01-02          1                   BEVERAGES  1856.00000   
1786  1947730  2016-01-02          1                       BOOKS     0.00000   
...       ...         ...        ...                         ...         ...   
3559  1949503  2016-01-02          9                     POULTRY   643.12897   
3560  1949504  2016-01-02          9              PREPARED FOODS   113.00000   
3561  1949505  2016-01-02          9                     PRODUCE  2029.37900   
3562  1949506  2016-01-02          9  SCHOOL AND OFFICE SUPPLIES     4.00000   
3563  1949507  2016-01-02          9                     SEAFOOD    24.14600   

      onpromotion  
1782          0.0  
1783          0.0  
1784          0.0  
1785          7.0  
1786          0.0  
...           ...  
3559          0.0  
3560          0.0  
3561          0.0  
3562          0.0  
3563          4.0  

[1782 rows x 6 columns]

In [369]:
retail.loc[retail['date']=='2016-02-05', ['store_nbr', 'sales']]

Empty DataFrame
Columns: [store_nbr, sales]
Index: []

In [370]:
mask = (retail['family'].isin(['BEAUTY', 'BOOKS'])) & (retail['sales']> 100)
retail.loc[mask]

Empty DataFrame
Columns: [id, date, store_nbr, family, sales, onpromotion]
Index: []

In [371]:
retail.loc[retail['date'].str[:7]=='2016-01']

id        date  store_nbr                      family  \
0      1945944  2016-01-01          1                  AUTOMOTIVE   
1      1945945  2016-01-01          1                   BABY CARE   
2      1945946  2016-01-01          1                      BEAUTY   
3      1945947  2016-01-01          1                   BEVERAGES   
4      1945948  2016-01-01          1                       BOOKS   
...        ...         ...        ...                         ...   
55237  2001181  2016-01-31          9                     POULTRY   
55238  2001182  2016-01-31          9              PREPARED FOODS   
55239  2001183  2016-01-31          9                     PRODUCE   
55240  2001184  2016-01-31          9  SCHOOL AND OFFICE SUPPLIES   
55241  2001185  2016-01-31          9                     SEAFOOD   

             sales  onpromotion  
0         0.000000          0.0  
1         0.000000          0.0  
2         0.000000          0.0  
3         0.000000          0.0  
4         0.000000          0.0  
...            ...          ...  
55237   500.384000          0.0  
55238   180.060000          0.0  
55239  2614.884000          0.0  
55240    17.000000          0.0  
55241    32.864998          0.0  

[55242 rows x 6 columns]

## .query()

In [372]:
retail

id        date  store_nbr                   family    sales  \
0      1945944  2016-01-01          1               AUTOMOTIVE    0.000   
1      1945945  2016-01-01          1                BABY CARE    0.000   
2      1945946  2016-01-01          1                   BEAUTY    0.000   
3      1945947  2016-01-01          1                BEVERAGES    0.000   
4      1945948  2016-01-01          1                    BOOKS    0.000   
...        ...         ...        ...                      ...      ...   
56092  2002036  2016-02-01         32            PERSONAL CARE  188.000   
56093  2002037  2016-02-01         32             PET SUPPLIES    0.000   
56094  2002038  2016-02-01         32  PLAYERS AND ELECTRONICS    0.000   
56095  2002039  2016-02-01         32                  POULTRY   79.261   
56096  2002040  2016-02-01         32                       PR      NaN   

       onpromotion  
0              0.0  
1              0.0  
2              0.0  
3              0.0  
4              0.0  
...            ...  
56092          0.0  
56093          0.0  
56094          0.0  
56095          0.0  
56096          NaN  

[56097 rows x 6 columns]

In [373]:
retail.query("family in ['BEAUTY', 'BOOKS'] and sales > 100")

Empty DataFrame
Columns: [id, date, store_nbr, family, sales, onpromotion]
Index: []

In [374]:
avg_sales = retail['sales'].mean()
avg_sales

433.19681553615413

In [375]:
retail.query("family in ['BEAUTY', 'BOOKS'] and sales < @avg_sales")

id        date  store_nbr  family  sales  onpromotion
2      1945946  2016-01-01          1  BEAUTY    0.0          0.0
4      1945948  2016-01-01          1   BOOKS    0.0          0.0
35     1945979  2016-01-01         10  BEAUTY    0.0          0.0
37     1945981  2016-01-01         10   BOOKS    0.0          0.0
68     1946012  2016-01-01         11  BEAUTY    0.0          0.0
...        ...         ...        ...     ...    ...          ...
56005  2001949  2016-02-01         30   BOOKS    0.0          0.0
56036  2001980  2016-02-01         31  BEAUTY    3.0          0.0
56038  2001982  2016-02-01         31   BOOKS    0.0          0.0
56069  2002013  2016-02-01         32  BEAUTY    1.0          0.0
56071  2002015  2016-02-01         32   BOOKS    0.0          0.0

[3400 rows x 6 columns]

## Sorting by index

In [376]:
condition = retail['family'].isin(['BEVERAGES', 'DIARY'])
sample_df = retail[condition].sample(5, random_state=2021)
sample_df

id        date  store_nbr     family   sales  onpromotion
12246  1958190  2016-01-07         52  BEVERAGES     0.0          0.0
42540  1988484  2016-01-24         52  BEVERAGES     0.0          0.0
2049   1947993  2016-01-02         17  BEVERAGES  4063.0          1.0
37293  1983237  2016-01-21          6  BEVERAGES  2573.0          0.0
37128  1983072  2016-01-21         50  BEVERAGES  2491.0          0.0

In [377]:
sample_df.sort_index(axis = 1, inplace = True)
sample_df

date     family       id  onpromotion   sales  store_nbr
12246  2016-01-07  BEVERAGES  1958190          0.0     0.0         52
42540  2016-01-24  BEVERAGES  1988484          0.0     0.0         52
2049   2016-01-02  BEVERAGES  1947993          1.0  4063.0         17
37293  2016-01-21  BEVERAGES  1983237          0.0  2573.0          6
37128  2016-01-21  BEVERAGES  1983072          0.0  2491.0         50

In [378]:
sample_df.sort_values('date')

date     family       id  onpromotion   sales  store_nbr
2049   2016-01-02  BEVERAGES  1947993          1.0  4063.0         17
12246  2016-01-07  BEVERAGES  1958190          0.0     0.0         52
37293  2016-01-21  BEVERAGES  1983237          0.0  2573.0          6
37128  2016-01-21  BEVERAGES  1983072          0.0  2491.0         50
42540  2016-01-24  BEVERAGES  1988484          0.0     0.0         52

In [379]:
sample_df.sort_values(['store_nbr', 'sales'], ascending=[True, True])

date     family       id  onpromotion   sales  store_nbr
37293  2016-01-21  BEVERAGES  1983237          0.0  2573.0          6
2049   2016-01-02  BEVERAGES  1947993          1.0  4063.0         17
37128  2016-01-21  BEVERAGES  1983072          0.0  2491.0         50
12246  2016-01-07  BEVERAGES  1958190          0.0     0.0         52
42540  2016-01-24  BEVERAGES  1988484          0.0     0.0         52

In [380]:
oil = pd.read_csv('/content/oil.csv')

In [381]:
oil['month'] = oil['date'].astype('datetime64[ns]').dt.month
oil

date  dcoilwtico  month
0     2013-01-01         NaN      1
1     2013-01-02       93.14      1
2     2013-01-03       92.97      1
3     2013-01-04       93.12      1
4     2013-01-07       93.20      1
...          ...         ...    ...
1213  2017-08-25       47.65      8
1214  2017-08-28       46.40      8
1215  2017-08-29       46.46      8
1216  2017-08-30       45.96      8
1217  2017-08-31       47.26      8

[1218 rows x 3 columns]

In [382]:
oil.sort_values('dcoilwtico')

date  dcoilwtico  month
812   2016-02-11       26.19      2
796   2016-01-20       26.68      1
811   2016-02-10       27.54      2
810   2016-02-09       27.96      2
795   2016-01-19       28.47      1
...          ...         ...    ...
1079  2017-02-20         NaN      2
1118  2017-04-14         NaN      4
1149  2017-05-29         NaN      5
1174  2017-07-03         NaN      7
1175  2017-07-04         NaN      7

[1218 rows x 3 columns]

In [383]:
oil.sort_values(['month', 'dcoilwtico'], ascending=[True, False])

date  dcoilwtico  month
282   2014-01-30       98.25      1
21    2013-01-30       97.98      1
22    2013-01-31       97.65      1
20    2013-01-29       97.62      1
283   2014-01-31       97.55      1
...          ...         ...    ...
774   2015-12-21       34.55     12
256   2013-12-25         NaN     12
517   2014-12-25         NaN     12
778   2015-12-25         NaN     12
1039  2016-12-26         NaN     12

[1218 rows x 3 columns]

## Renaming and Reordering columns

In [384]:
product_df = pd.DataFrame({'Product': ['Diary', 'Diary', 'Diary', 'Vegetables', 'Fruits'],
                           'Price' : [2.56, 2.56, 4.55, 2.74, 5.44]})

product_df

Product  Price
0       Diary   2.56
1       Diary   2.56
2       Diary   4.55
3  Vegetables   2.74
4      Fruits   5.44

In [385]:
product_df.columns = ['Product_name', 'Cost']

In [386]:
product_df.columns = [col.upper() for col in product_df.columns]
product_df

PRODUCT_NAME  COST
0        Diary  2.56
1        Diary  2.56
2        Diary  4.55
3   Vegetables  2.74
4       Fruits  5.44

In [387]:
product_df.rename(columns={'PRODUCT_NAME' :'Product', 'COST':'Price'})

Product  Price
0       Diary   2.56
1       Diary   2.56
2       Diary   4.55
3  Vegetables   2.74
4      Fruits   5.44

In [388]:
product_df.rename(columns= lambda x: x.upper())

PRODUCT_NAME  COST
0        Diary  2.56
1        Diary  2.56
2        Diary  4.55
3   Vegetables  2.74
4       Fruits  5.44

## creating arithmetic columns

In [389]:
import pandas as pd
oil = pd.read_csv('/content/oil.csv').dropna()
oil.reset_index(inplace= True)

In [390]:
oil.sort_values('date', ascending=True)
oil.drop(0,axis=0)

index        date  dcoilwtico
1         2  2013-01-03       92.97
2         3  2013-01-04       93.12
3         4  2013-01-07       93.20
4         5  2013-01-08       93.21
5         6  2013-01-09       93.08
...     ...         ...         ...
1170   1213  2017-08-25       47.65
1171   1214  2017-08-28       46.40
1172   1215  2017-08-29       46.46
1173   1216  2017-08-30       45.96
1174   1217  2017-08-31       47.26

[1174 rows x 3 columns]

In [391]:
oil['benchmark'] = 90
oil

index        date  dcoilwtico  benchmark
0         1  2013-01-02       93.14         90
1         2  2013-01-03       92.97         90
2         3  2013-01-04       93.12         90
3         4  2013-01-07       93.20         90
4         5  2013-01-08       93.21         90
...     ...         ...         ...        ...
1170   1213  2017-08-25       47.65         90
1171   1214  2017-08-28       46.40         90
1172   1215  2017-08-29       46.46         90
1173   1216  2017-08-30       45.96         90
1174   1217  2017-08-31       47.26         90

[1175 rows x 4 columns]

In [392]:
oil['benchmark_ratio'] = oil.loc[:,'dcoilwtico'] / oil.loc[:,'benchmark']
oil

index        date  dcoilwtico  benchmark  benchmark_ratio
0         1  2013-01-02       93.14         90         1.034889
1         2  2013-01-03       92.97         90         1.033000
2         3  2013-01-04       93.12         90         1.034667
3         4  2013-01-07       93.20         90         1.035556
4         5  2013-01-08       93.21         90         1.035667
...     ...         ...         ...        ...              ...
1170   1213  2017-08-25       47.65         90         0.529444
1171   1214  2017-08-28       46.40         90         0.515556
1172   1215  2017-08-29       46.46         90         0.516222
1173   1216  2017-08-30       45.96         90         0.510667
1174   1217  2017-08-31       47.26         90         0.525111

[1175 rows x 5 columns]

In [393]:
oil['buy']= oil['benchmark_ratio'] < 1
oil

index        date  dcoilwtico  benchmark  benchmark_ratio    buy
0         1  2013-01-02       93.14         90         1.034889  False
1         2  2013-01-03       92.97         90         1.033000  False
2         3  2013-01-04       93.12         90         1.034667  False
3         4  2013-01-07       93.20         90         1.035556  False
4         5  2013-01-08       93.21         90         1.035667  False
...     ...         ...         ...        ...              ...    ...
1170   1213  2017-08-25       47.65         90         0.529444   True
1171   1214  2017-08-28       46.40         90         0.515556   True
1172   1215  2017-08-29       46.46         90         0.516222   True
1173   1216  2017-08-30       45.96         90         0.510667   True
1174   1217  2017-08-31       47.26         90         0.525111   True

[1175 rows x 6 columns]

## Select function

In [394]:
import numpy as np


In [395]:
oil = pd.read_csv('/content/oil.csv')

oil.rename(columns = {'dcoilwtico': 'price'}, inplace=True)

In [396]:
conditions=  [oil['price']>  100,
              (oil['price']<= 100) & (oil['price']> 50),
              oil['price']<=50]

choices = ['Too High', 'Think', 'Definitely Buy']

oil['new'] = np.select(conditions, choices, default = 'No Data')
oil


date  price             new
0     2013-01-01    NaN         No Data
1     2013-01-02  93.14           Think
2     2013-01-03  92.97           Think
3     2013-01-04  93.12           Think
4     2013-01-07  93.20           Think
...          ...    ...             ...
1213  2017-08-25  47.65  Definitely Buy
1214  2017-08-28  46.40  Definitely Buy
1215  2017-08-29  46.46  Definitely Buy
1216  2017-08-30  45.96  Definitely Buy
1217  2017-08-31  47.26  Definitely Buy

[1218 rows x 3 columns]

## Mapping values to columns

In [397]:
mapping_dict = {'Diary': 'Non-vegan', 'Vegetables':'Vegan', 'Fruits':'Vegan'}

product_df = pd.DataFrame({'Product': ['Diary', 'Diary', 'Diary', 'Vegetables', 'Fruits'],
                           'Price': [2.56,2.56,4.55,2.74,5.44]})

In [398]:
product_df['Vegan?'] = product_df['Product'].map(mapping_dict)
product_df

Product  Price     Vegan?
0       Diary   2.56  Non-vegan
1       Diary   2.56  Non-vegan
2       Diary   4.55  Non-vegan
3  Vegetables   2.74      Vegan
4      Fruits   5.44      Vegan

## assign()

In [399]:
retail = pd.read_csv('/content/retail_2016_2017.csv')
sample_df = retail.sample(5, random_state=85)
sample_df

id        date  store_nbr                   family  sales  \
23874  1969818  2016-01-14       29.0       HOME AND KITCHEN I   17.0   
69157  2015101  2016-02-08       49.0         LIQUOR,WINE,BEER  382.0   
13122  1959066  2016-01-08       27.0                 LINGERIE    2.0   
5534   1951478  2016-01-04       14.0                MAGAZINES    0.0   
17550  1963494  2016-01-10       50.0  PLAYERS AND ELECTRONICS   41.0   

       onpromotion  
23874          0.0  
69157          1.0  
13122          0.0  
5534           0.0  
17550          0.0

In [400]:
sample_df = sample_df.assign(onpormoflag = sample_df['onpromotion']>0,
                 familyabr = sample_df['family'].str[:3],
                 onpromoratio = sample_df['sales']/sample_df['onpromotion'],
                 salesonpro_target = lambda x: x['onpromoratio']>100)

sample_df

id        date  store_nbr                   family  sales  \
23874  1969818  2016-01-14       29.0       HOME AND KITCHEN I   17.0   
69157  2015101  2016-02-08       49.0         LIQUOR,WINE,BEER  382.0   
13122  1959066  2016-01-08       27.0                 LINGERIE    2.0   
5534   1951478  2016-01-04       14.0                MAGAZINES    0.0   
17550  1963494  2016-01-10       50.0  PLAYERS AND ELECTRONICS   41.0   

       onpromotion  onpormoflag familyabr  onpromoratio  salesonpro_target  
23874          0.0        False       HOM           inf               True  
69157          1.0         True       LIQ         382.0               True  
13122          0.0        False       LIN           inf               True  
5534           0.0        False       MAG           NaN              False  
17550          0.0        False       PLA           inf               True

## Type Conversion

In [401]:
sample_df.astype({'date': 'datetime64[ns]', 'onpromotion':'float'})

id       date  store_nbr                   family  sales  \
23874  1969818 2016-01-14       29.0       HOME AND KITCHEN I   17.0   
69157  2015101 2016-02-08       49.0         LIQUOR,WINE,BEER  382.0   
13122  1959066 2016-01-08       27.0                 LINGERIE    2.0   
5534   1951478 2016-01-04       14.0                MAGAZINES    0.0   
17550  1963494 2016-01-10       50.0  PLAYERS AND ELECTRONICS   41.0   

       onpromotion  onpormoflag familyabr  onpromoratio  salesonpro_target  
23874          0.0        False       HOM           inf               True  
69157          1.0         True       LIQ         382.0               True  
13122          0.0        False       LIN           inf               True  
5534           0.0        False       MAG           NaN              False  
17550          0.0        False       PLA           inf               True

In [402]:
product_df['Price'] = product_df['Price'].apply(lambda x: f"${x}")
product_df

Product  Price     Vegan?
0       Diary  $2.56  Non-vegan
1       Diary  $2.56  Non-vegan
2       Diary  $4.55  Non-vegan
3  Vegetables  $2.74      Vegan
4      Fruits  $5.44      Vegan

In [403]:
product_df.assign(
    new = product_df['Price'].str.strip('$').astype('float').astype('int')
)

Product  Price     Vegan?  new
0       Diary  $2.56  Non-vegan    2
1       Diary  $2.56  Non-vegan    2
2       Diary  $4.55  Non-vegan    4
3  Vegetables  $2.74      Vegan    2
4      Fruits  $5.44      Vegan    5

# Aggregating data frames

In [404]:
retail.loc[:,['sales', 'onpromotion']].sample(100).sum().round(2)

sales          34792.26
onpromotion      211.00
dtype: float64

## Gruoup_by()

In [405]:
retail.groupby('family')['sales'].sum().sort_values(ascending=False).head()

family
GROCERY I    9.249982e+06
BEVERAGES    7.165902e+06
PRODUCE      5.409683e+06
CLEANING     2.736816e+06
DAIRY        1.837618e+06
Name: sales, dtype: float64

In [406]:
sales_sum = retail.groupby(['family', 'store_nbr'])['sales'].agg(['sum', 'mean'])
sales_sum

sum       mean
family     store_nbr                        
AUTOMOTIVE 1.0         193.000000   4.488372
           2.0         309.000000   7.186047
           3.0         547.000000  12.720930
           4.0         188.000000   4.372093
           5.0         296.000000   6.883721
...                           ...        ...
SEAFOOD    50.0        905.281000  21.053047
           51.0       2893.273988  67.285442
           52.0          0.000000   0.000000
           53.0        142.876000   3.322698
           54.0         56.000000   1.333333

[1782 rows x 2 columns]

## Multi index

In [407]:
sales_sum.index

MultiIndex([('AUTOMOTIVE',  1.0),
            ('AUTOMOTIVE',  2.0),
            ('AUTOMOTIVE',  3.0),
            ('AUTOMOTIVE',  4.0),
            ('AUTOMOTIVE',  5.0),
            ('AUTOMOTIVE',  6.0),
            ('AUTOMOTIVE',  7.0),
            ('AUTOMOTIVE',  8.0),
            ('AUTOMOTIVE',  9.0),
            ('AUTOMOTIVE', 10.0),
            ...
            (   'SEAFOOD', 45.0),
            (   'SEAFOOD', 46.0),
            (   'SEAFOOD', 47.0),
            (   'SEAFOOD', 48.0),
            (   'SEAFOOD', 49.0),
            (   'SEAFOOD', 50.0),
            (   'SEAFOOD', 51.0),
            (   'SEAFOOD', 52.0),
            (   'SEAFOOD', 53.0),
            (   'SEAFOOD', 54.0)],
           names=['family', 'store_nbr'], length=1782)

In [408]:
sales_sum.loc['AUTOMOTIVE'].head()

sum       mean
store_nbr                  
1.0        193.0   4.488372
2.0        309.0   7.186047
3.0        547.0  12.720930
4.0        188.0   4.372093
5.0        296.0   6.883721

In [409]:
sales_sum.loc[['AUTOMOTIVE', 'SEAFOOD']]

sum       mean
family     store_nbr                        
AUTOMOTIVE 1.0         193.000000   4.488372
           2.0         309.000000   7.186047
           3.0         547.000000  12.720930
           4.0         188.000000   4.372093
           5.0         296.000000   6.883721
...                           ...        ...
SEAFOOD    50.0        905.281000  21.053047
           51.0       2893.273988  67.285442
           52.0          0.000000   0.000000
           53.0        142.876000   3.322698
           54.0         56.000000   1.333333

[108 rows x 2 columns]

In [410]:
sales_sum.loc[[('AUTOMOTIVE',12), ('SEAFOOD',12)]]

sum      mean
family     store_nbr                 
AUTOMOTIVE 12.0       302.0  7.023256
SEAFOOD    12.0        99.0  2.302326

## Modifying multi index

### reset the index

In [411]:
sales_sum.reset_index()


family  store_nbr          sum       mean
0     AUTOMOTIVE        1.0   193.000000   4.488372
1     AUTOMOTIVE        2.0   309.000000   7.186047
2     AUTOMOTIVE        3.0   547.000000  12.720930
3     AUTOMOTIVE        4.0   188.000000   4.372093
4     AUTOMOTIVE        5.0   296.000000   6.883721
...          ...        ...          ...        ...
1777     SEAFOOD       50.0   905.281000  21.053047
1778     SEAFOOD       51.0  2893.273988  67.285442
1779     SEAFOOD       52.0     0.000000   0.000000
1780     SEAFOOD       53.0   142.876000   3.322698
1781     SEAFOOD       54.0    56.000000   1.333333

[1782 rows x 4 columns]

### swap index

In [412]:
sales_sum.swaplevel()

sum       mean
store_nbr family                            
1.0       AUTOMOTIVE   193.000000   4.488372
2.0       AUTOMOTIVE   309.000000   7.186047
3.0       AUTOMOTIVE   547.000000  12.720930
4.0       AUTOMOTIVE   188.000000   4.372093
5.0       AUTOMOTIVE   296.000000   6.883721
...                           ...        ...
50.0      SEAFOOD      905.281000  21.053047
51.0      SEAFOOD     2893.273988  67.285442
52.0      SEAFOOD        0.000000   0.000000
53.0      SEAFOOD      142.876000   3.322698
54.0      SEAFOOD       56.000000   1.333333

[1782 rows x 2 columns]

### drop index level

In [413]:
sales_sum.droplevel('family')

sum       mean
store_nbr                        
1.0         193.000000   4.488372
2.0         309.000000   7.186047
3.0         547.000000  12.720930
4.0         188.000000   4.372093
5.0         296.000000   6.883721
...                ...        ...
50.0        905.281000  21.053047
51.0       2893.273988  67.285442
52.0          0.000000   0.000000
53.0        142.876000   3.322698
54.0         56.000000   1.333333

[1782 rows x 2 columns]

In [414]:
sales_sum = retail.groupby(['family', 'store_nbr'])['sales'].agg(['sum', 'mean'])
sales_sum


sum       mean
family     store_nbr                        
AUTOMOTIVE 1.0         193.000000   4.488372
           2.0         309.000000   7.186047
           3.0         547.000000  12.720930
           4.0         188.000000   4.372093
           5.0         296.000000   6.883721
...                           ...        ...
SEAFOOD    50.0        905.281000  21.053047
           51.0       2893.273988  67.285442
           52.0          0.000000   0.000000
           53.0        142.876000   3.322698
           54.0         56.000000   1.333333

[1782 rows x 2 columns]

In [415]:
sales_sum.loc['AUTOMOTIVE']

sum       mean
store_nbr                  
1.0        193.0   4.488372
2.0        309.0   7.186047
3.0        547.0  12.720930
4.0        188.0   4.372093
5.0        296.0   6.883721
6.0        288.0   6.857143
7.0        220.0   5.238095
8.0        288.0   6.857143
9.0        703.0  16.738095
10.0       207.0   4.813953
11.0       359.0   8.348837
12.0       302.0   7.023256
13.0       230.0   5.348837
14.0       176.0   4.093023
15.0       145.0   3.372093
16.0       305.0   7.093023
17.0       205.0   4.767442
18.0       194.0   4.511628
19.0       341.0   7.930233
20.0       429.0   9.976744
21.0       460.0  10.697674
22.0       221.0   5.139535
23.0        84.0   1.953488
24.0       178.0   4.139535
25.0       133.0   3.093023
26.0       205.0   4.767442
27.0       322.0   7.488372
28.0       353.0   8.209302
29.0       316.0   7.348837
30.0       151.0   3.511628
31.0       551.0  12.813953
32.0       113.0   2.627907
33.0       359.0   8.348837
34.0       171.0   3.976744
35.0       303.0   7.046512
36.0       240.0   5.581395
37.0       252.0   5.860465
38.0       300.0   6.976744
39.0       374.0   8.697674
40.0       205.0   4.767442
41.0       246.0   5.720930
42.0       153.0   3.558140
43.0       417.0   9.697674
44.0       763.0  17.744186
45.0       703.0  16.348837
46.0       703.0  16.348837
47.0       725.0  16.860465
48.0       683.0  15.883721
49.0       430.0  10.000000
50.0       370.0   8.604651
51.0       301.0   7.000000
52.0         0.0   0.000000
53.0       241.0   5.604651
54.0       315.0   7.325581

## Naming aggregated columns

In [416]:
# Group by 'family' and 'store_nbr' and compute multiple aggregations
sales_sum = retail.groupby(['family', 'store_nbr'], as_index=False).agg(
    sales_sums=('sales', 'sum'),
    sales_mean=('sales', 'mean'),
    onpromo_max=('onpromotion', 'max')
)
sales_sum

family  store_nbr   sales_sums  sales_mean  onpromo_max
0     AUTOMOTIVE        1.0   193.000000    4.488372          0.0
1     AUTOMOTIVE        2.0   309.000000    7.186047          0.0
2     AUTOMOTIVE        3.0   547.000000   12.720930          0.0
3     AUTOMOTIVE        4.0   188.000000    4.372093          0.0
4     AUTOMOTIVE        5.0   296.000000    6.883721          0.0
...          ...        ...          ...         ...          ...
1777     SEAFOOD       50.0   905.281000   21.053047          6.0
1778     SEAFOOD       51.0  2893.273988   67.285442          7.0
1779     SEAFOOD       52.0     0.000000    0.000000          0.0
1780     SEAFOOD       53.0   142.876000    3.322698          3.0
1781     SEAFOOD       54.0    56.000000    1.333333          2.0

[1782 rows x 5 columns]

## transform()

In [417]:
trans = pd.read_csv('/content/transactions.csv')
trans.head(3)

date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358

In [418]:
trans= trans.assign(trans_sales = trans.groupby('store_nbr')['transactions'].transform('sum'))
trans.head(3)
trans.loc[trans['store_nbr']==25]

date  store_nbr  transactions  trans_sales
0      2013-01-01         25           770      1520362
22     2013-01-02         25          1038      1520362
68     2013-01-03         25           887      1520362
114    2013-01-04         25          1054      1520362
160    2013-01-05         25          1355      1520362
...           ...        ...           ...          ...
83242  2017-08-11         25          2195      1520362
83296  2017-08-12         25          1946      1520362
83350  2017-08-13         25          1107      1520362
83404  2017-08-14         25           935      1520362
83458  2017-08-15         25           849      1520362

[1615 rows x 4 columns]

## Pivot table

In [419]:
retail = pd.read_csv('/content/retail_2016_2017.csv')

retail.pivot_table(
    index = 'family',
    columns = 'date',
    values = 'sales',
    aggfunc = 'sum'
)

date                        2016-01-01     2016-01-02     2016-01-03  \
family                                                                 
AUTOMOTIVE                       4.000     625.000000     661.000000   
BABY CARE                        0.000       9.000000      17.000000   
BEAUTY                          13.000     382.000000     424.000000   
BEVERAGES                     5104.000  250510.000000  299177.000000   
BOOKS                            0.000       0.000000       0.000000   
BREAD/BAKERY                   680.952   33464.574020   40905.380030   
CELEBRATION                     13.000    1040.000000     732.000000   
CLEANING                       734.000   93377.000000  103544.000000   
DAIRY                         1033.000   55039.000000   68371.000000   
DELI                           295.181   22591.372000   25365.567000   
EGGS                           230.000   12032.000000   14589.000000   
FROZEN FOODS                   596.125   11795.280978   11447.520994   
GROCERY I                     3247.000  309417.194000  347681.912000   
GROCERY II                      28.000    1886.000000    1882.000000   
HARDWARE                         4.000     106.000000     104.000000   
HOME AND KITCHEN I              61.000    2525.000000    1915.000000   
HOME AND KITCHEN II              6.000    1760.000000    1663.000000   
HOME APPLIANCES                  1.000      54.000000      51.000000   
HOME CARE                      217.000   24518.000000   27415.000000   
LADIESWEAR                       0.000     959.000000    1504.000000   
LAWN AND GARDEN                 11.000     368.000000     295.000000   
LINGERIE                        17.000     406.000000     356.000000   
LIQUOR,WINE,BEER               733.000    9517.000000       0.000000   
MAGAZINES                       16.000     359.000000     282.000000   
MEATS                          397.749   22850.042968   24417.722000   
PERSONAL CARE                  226.000   29527.000000   33843.000000   
PET SUPPLIES                     2.000     419.000000     465.000000   
PLAYERS AND ELECTRONICS         10.000     749.000000     863.000000   
POULTRY                        261.179   25309.535876   26105.507950   
PREPARED FOODS                  94.699    7329.263020    7224.984024   
PRODUCE                       2384.509  146126.164000  183392.022900   
SCHOOL AND OFFICE SUPPLIES       0.000     145.000000     223.000000   
SEAFOOD                         13.000    1481.998000    1819.102997   

date                           2016-01-04     2016-01-05     2016-01-06  \
family                                                                    
AUTOMOTIVE                     407.000000     338.000000     358.000000   
BABY CARE                       18.000000       4.000000       6.000000   
BEAUTY                         296.000000     279.000000     191.000000   
BEVERAGES                   217525.000000  187069.000000  170360.000000   
BOOKS                            0.000000       0.000000       0.000000   
BREAD/BAKERY                 31278.867970   27189.876970   25631.930100   
CELEBRATION                    575.000000     616.000000     711.000000   
CLEANING                     83979.000000   72688.000000   67105.000000   
DAIRY                        52242.000000   45174.000000   44103.000000   
DELI                         18488.887000   16308.949000   14417.930000   
EGGS                         12998.000000    9357.000000    8484.000000   
FROZEN FOODS                  8546.223000    8191.186000    8208.030982   
GROCERY I                   272978.806000  234212.722000  220632.777000   
GROCERY II                    1273.000000    1297.000000    1161.000000   
HARDWARE                        82.000000      65.000000      61.000000   
HOME AND KITCHEN I            1508.000000    1432.000000    1530.000000   
HOME AND KITCHEN II           1303.000000    1346.000000    1448.000000   
HOME APPLIANCES                 33.000000      23.0000

In [420]:
retail.query("family in ['AUTOMOTIVE', 'BEVERAGES', 'BEAUTY'] and date in ['2016-01-01', '2016-01-02','2016-01-03']").pivot_table(
    index = 'family',
    columns = 'date',
    values = 'sales',
    aggfunc = 'sum',
    margins = True
)

date        2016-01-01  2016-01-02  2016-01-03       All
family                                                  
AUTOMOTIVE         4.0       625.0       661.0    1290.0
BEAUTY            13.0       382.0       424.0     819.0
BEVERAGES       5104.0    250510.0    299177.0  554791.0
All             5121.0    251517.0    300262.0  556900.0

In [421]:
retail.query("family in ['AUTOMOTIVE', 'BEVERAGES', 'BEAUTY'] and date in ['2016-01-01', '2016-01-02','2016-01-03']").pivot_table(
    index = 'family',
    columns = 'date',
    values = 'sales',
    aggfunc = ('min', 'max')
)

max                              min                      
date       2016-01-01 2016-01-02 2016-01-03 2016-01-01 2016-01-02 2016-01-03
family                                                                      
AUTOMOTIVE        4.0       43.0       46.0        0.0        0.0        0.0
BEAUTY           13.0       33.0       39.0        0.0        0.0        0.0
BEVERAGES      5104.0    16468.0    19799.0        0.0        0.0        0.0

In [422]:
retail.query("family in ['AUTOMOTIVE', 'BEVERAGES', 'BEAUTY'] and date in ['2016-01-01', '2016-01-02','2016-01-03']").pivot_table(
    index = 'family',
    columns = 'date',
    aggfunc = ({'sales':['sum', 'mean'], 'onpromotion' :['max']})
)

onpromotion                            sales               \
                   max                             mean                
date        2016-01-01 2016-01-02 2016-01-03 2016-01-01   2016-01-02   
family                                                                 
AUTOMOTIVE         0.0        0.0        0.0   0.074074    11.574074   
BEAUTY             0.0        2.0        2.0   0.240741     7.074074   
BEVERAGES          1.0        8.0        9.0  94.518519  4639.074074   

                                                          
                               sum                        
date         2016-01-03 2016-01-01 2016-01-02 2016-01-03  
family                                                    
AUTOMOTIVE    12.240741        4.0      625.0      661.0  
BEAUTY         7.851852       13.0      382.0      424.0  
BEVERAGES   5540.314815     5104.0   250510.0   299177.0

## heatmap

In [423]:
retail.query("family in ['AUTOMOTIVE', 'BEVERAGES', 'BEAUTY'] and date in ['2016-01-01', '2016-01-02','2016-01-03']").pivot_table(
    index = 'family',
    columns = 'date',
    values = 'sales',
    aggfunc = 'sum',
    margins = True
).style.background_gradient(cmap = 'RdYlGn', axis=None)

In [424]:
pivt = retail.query("family in ['AUTOMOTIVE', 'BEVERAGES', 'BEAUTY'] and date in ['2016-01-01', '2016-01-02','2016-01-03']").pivot_table(
    index = 'family',
    columns = 'date',
    values = 'sales',
    aggfunc = 'sum',
    margins = True
).style.background_gradient(cmap = 'RdYlGn', axis=1)
pivt

## melt()

In [425]:
pivt = retail.query("family in ['AUTOMOTIVE', 'BEVERAGES', 'BEAUTY'] and date in ['2016-01-01', '2016-01-02','2016-01-03']").pivot_table(
    index = 'family',
    columns = 'date',
    values = 'sales',
    aggfunc = 'sum',
    margins = True
)
pivt

date        2016-01-01  2016-01-02  2016-01-03       All
family                                                  
AUTOMOTIVE         4.0       625.0       661.0    1290.0
BEAUTY            13.0       382.0       424.0     819.0
BEVERAGES       5104.0    250510.0    299177.0  554791.0
All             5121.0    251517.0    300262.0  556900.0

In [426]:
pivt.reset_index().melt(
    id_vars ='family',
)

family        date     value
0   AUTOMOTIVE  2016-01-01       4.0
1       BEAUTY  2016-01-01      13.0
2    BEVERAGES  2016-01-01    5104.0
3          All  2016-01-01    5121.0
4   AUTOMOTIVE  2016-01-02     625.0
5       BEAUTY  2016-01-02     382.0
6    BEVERAGES  2016-01-02  250510.0
7          All  2016-01-02  251517.0
8   AUTOMOTIVE  2016-01-03     661.0
9       BEAUTY  2016-01-03     424.0
10   BEVERAGES  2016-01-03  299177.0
11         All  2016-01-03  300262.0
12  AUTOMOTIVE         All    1290.0
13      BEAUTY         All     819.0
14   BEVERAGES         All  554791.0
15         All         All  556900.0

In [427]:
pivt.reset_index().melt(
    id_vars ='family',
    value_vars=['2016-01-01'],
    value_name= 'sum sales'
)

family        date  sum sales
0  AUTOMOTIVE  2016-01-01        4.0
1      BEAUTY  2016-01-01       13.0
2   BEVERAGES  2016-01-01     5104.0
3         All  2016-01-01     5121.0

# Date time handling

In [428]:
from datetime import datetime

In [429]:
datetime.now()

datetime.datetime(2024, 12, 23, 9, 36, 31, 689845)

In [430]:
retail = pd.read_csv('/content/retail_2016_2017.csv')
retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76494 entries, 0 to 76493
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           76494 non-null  int64  
 1   date         76493 non-null  object 
 2   store_nbr    76493 non-null  float64
 3   family       76493 non-null  object 
 4   sales        76493 non-null  float64
 5   onpromotion  76493 non-null  float64
dtypes: float64(3), int64(1), object(2)
memory usage: 3.5+ MB


In [431]:
retail.loc[0,['date']] = 'N/A'
retail

id        date  store_nbr                      family      sales  \
0      1945944         N/A        1.0                  AUTOMOTIVE    0.00000   
1      1945945  2016-01-01        1.0                   BABY CARE    0.00000   
2      1945946  2016-01-01        1.0                      BEAUTY    0.00000   
3      1945947  2016-01-01        1.0                   BEVERAGES    0.00000   
4      1945948  2016-01-01        1.0                       BOOKS    0.00000   
...        ...         ...        ...                         ...        ...   
76489  2022433  2016-02-12       54.0                     POULTRY   43.12000   
76490  2022434  2016-02-12       54.0              PREPARED FOODS   27.00000   
76491  2022435  2016-02-12       54.0                     PRODUCE  476.16602   
76492  2022436  2016-02-12       54.0  SCHOOL AND OFFICE SUPPLIES    0.00000   
76493  2022437         NaN        NaN                         NaN        NaN   

       onpromotion  
0              0.0  
1              0.0  
2              0.0  
3              0.0  
4              0.0  
...            ...  
76489          6.0  
76490          0.0  
76491          0.0  
76492          0.0  
76493          NaN  

[76494 rows x 6 columns]

In [432]:
retail['date'] = pd.to_datetime(retail['date'],
                                errors = 'coerce',
                                infer_datetime_format=True)

retail

<ipython-input-432-b5f80870c5c1>:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  retail['date'] = pd.to_datetime(retail['date'],
<ipython-input-432-b5f80870c5c1>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  retail['date'] = pd.to_datetime(retail['date'],


id       date  store_nbr                      family      sales  \
0      1945944        NaT        1.0                  AUTOMOTIVE    0.00000   
1      1945945 2016-01-01        1.0                   BABY CARE    0.00000   
2      1945946 2016-01-01        1.0                      BEAUTY    0.00000   
3      1945947 2016-01-01        1.0                   BEVERAGES    0.00000   
4      1945948 2016-01-01        1.0                       BOOKS    0.00000   
...        ...        ...        ...                         ...        ...   
76489  2022433 2016-02-12       54.0                     POULTRY   43.12000   
76490  2022434 2016-02-12       54.0              PREPARED FOODS   27.00000   
76491  2022435 2016-02-12       54.0                     PRODUCE  476.16602   
76492  2022436 2016-02-12       54.0  SCHOOL AND OFFICE SUPPLIES    0.00000   
76493  2022437        NaT        NaN                         NaN        NaN   

       onpromotion  
0              0.0  
1              0.0  
2              0.0  
3              0.0  
4              0.0  
...            ...  
76489          6.0  
76490          0.0  
76491          0.0  
76492          0.0  
76493          NaN  

[76494 rows x 6 columns]

In [433]:
retail = retail.assign(
    date = (retail['date'].dt.strftime('%y-%B-%a'))
)

retail

id             date  store_nbr                      family  \
0      1945944              NaN        1.0                  AUTOMOTIVE   
1      1945945   16-January-Fri        1.0                   BABY CARE   
2      1945946   16-January-Fri        1.0                      BEAUTY   
3      1945947   16-January-Fri        1.0                   BEVERAGES   
4      1945948   16-January-Fri        1.0                       BOOKS   
...        ...              ...        ...                         ...   
76489  2022433  16-February-Fri       54.0                     POULTRY   
76490  2022434  16-February-Fri       54.0              PREPARED FOODS   
76491  2022435  16-February-Fri       54.0                     PRODUCE   
76492  2022436  16-February-Fri       54.0  SCHOOL AND OFFICE SUPPLIES   
76493  2022437              NaN        NaN                         NaN   

           sales  onpromotion  
0        0.00000          0.0  
1        0.00000          0.0  
2        0.00000          0.0  
3        0.00000          0.0  
4        0.00000          0.0  
...          ...          ...  
76489   43.12000          6.0  
76490   27.00000          0.0  
76491  476.16602          0.0  
76492    0.00000          0.0  
76493        NaN          NaN  

[76494 rows x 6 columns]

# read files

## Converters

In [434]:
missing = lambda x: x if x not in [''] else 0
currency = lambda x: f"${x}.00"

oil = pd.read_csv('/content/oil2.csv',
                  names = ['date', 'oilprice','new'],
                  parse_dates= True,
                  header = None,
                  #skiprows=[0],
                  converters = {'oilprice':missing, 'new':currency})

oil


date    oilprice       new
0          date  dcoilwtico   $new.00
1      1/1/2013           0     $1.00
2      1/2/2013       93.14     $2.00
3      1/3/2013       92.97     $3.00
4      1/4/2013       93.12     $4.00
...         ...         ...       ...
1214  8/25/2017       47.65  $1214.00
1215  8/28/2017        46.4  $1215.00
1216  8/29/2017       46.46  $1216.00
1217  8/30/2017       45.96  $1217.00
1218  8/31/2017       47.26  $1218.00

[1219 rows x 3 columns]

# Export files

In [435]:
trans = pd.read_csv('/content/transactions.csv',
                    parse_dates=['Date'],
                    names = ['Date','Store_number', 'Transaction_count'],
                    skiprows = [0],
                    dtype = {'Store_number':'int8', 'Transaction_count':'int16'}).assign(
                    target_pct = lambda x: (x['Transaction_count']/2500),
                    met_target = lambda x: ((x['Transaction_count']/2500) >=1),
                    bonus_payable = lambda x: (((x['Transaction_count']/2500) >=1)*100),
                    month = lambda x: (x['Date'].dt.month),
                    day_of_week = lambda x: (x['Date'].dt.dayofweek)).astype({'target_pct':'Float32',
                                                                              'month':'int8',
                                                                              'day_of_week':'int8'})

trans.to_csv('cleaned.csv')

## SQL databases

In [436]:
from sqlalchemy import create_engine, inspect
engine = create_engine('sqlite:///../soccer_database.sqlite')
inspect(engine).get_table_names()

[]

# Combining data frames

In [437]:
automotive = retail.query("family == 'AUTOMOTIVE'").head()

In [438]:
beauty = retail.query("family == 'BEAUTY'").head()

In [439]:
pd.concat([automotive, beauty])

id            date  store_nbr      family  sales  onpromotion
0    1945944             NaN        1.0  AUTOMOTIVE    0.0          0.0
33   1945977  16-January-Fri       10.0  AUTOMOTIVE    0.0          0.0
66   1946010  16-January-Fri       11.0  AUTOMOTIVE    0.0          0.0
99   1946043  16-January-Fri       12.0  AUTOMOTIVE    0.0          0.0
132  1946076  16-January-Fri       13.0  AUTOMOTIVE    0.0          0.0
2    1945946  16-January-Fri        1.0      BEAUTY    0.0          0.0
35   1945979  16-January-Fri       10.0      BEAUTY    0.0          0.0
68   1946012  16-January-Fri       11.0      BEAUTY    0.0          0.0
101  1946045  16-January-Fri       12.0      BEAUTY    0.0          0.0
134  1946078  16-January-Fri       13.0      BEAUTY    0.0          0.0

In [440]:
pd.concat([automotive, beauty],
          ignore_index = True)

id            date  store_nbr      family  sales  onpromotion
0  1945944             NaN        1.0  AUTOMOTIVE    0.0          0.0
1  1945977  16-January-Fri       10.0  AUTOMOTIVE    0.0          0.0
2  1946010  16-January-Fri       11.0  AUTOMOTIVE    0.0          0.0
3  1946043  16-January-Fri       12.0  AUTOMOTIVE    0.0          0.0
4  1946076  16-January-Fri       13.0  AUTOMOTIVE    0.0          0.0
5  1945946  16-January-Fri        1.0      BEAUTY    0.0          0.0
6  1945979  16-January-Fri       10.0      BEAUTY    0.0          0.0
7  1946012  16-January-Fri       11.0      BEAUTY    0.0          0.0
8  1946045  16-January-Fri       12.0      BEAUTY    0.0          0.0
9  1946078  16-January-Fri       13.0      BEAUTY    0.0          0.0

## merge

In [445]:
oil = pd.read_csv('/content/oil.csv')
trans = pd.read_csv('/content/transactions.csv')
trans.merge(oil,
            how = 'inner',
            left_on = ['date'],
            right_on = ['date']).loc[trans['date']=='2013-01-02']

date  store_nbr  transactions  dcoilwtico
1   2013-01-02          1          2111       93.14
2   2013-01-02          2          2358       93.14
3   2013-01-02          3          3487       93.14
4   2013-01-02          4          1922       93.14
5   2013-01-02          5          1903       93.14
6   2013-01-02          6          2143       93.14
7   2013-01-02          7          1874       93.14
8   2013-01-02          8          3250       93.14
9   2013-01-02          9          2940       93.14
10  2013-01-02         10          1293       93.14
11  2013-01-02         11          3547       93.14
12  2013-01-02         12          1362       93.14
13  2013-01-02         13          1102       93.14
14  2013-01-02         14          2002       93.14
15  2013-01-02         15          1622       93.14
16  2013-01-02         16          1167       93.14
17  2013-01-02         17          1580       93.14
18  2013-01-02         18          1635       93.14
19  2013-01-02         19          1369       93.14
20  2013-01-02         23          1381       93.14
21  2013-01-02         24          2605       93.14
22  2013-01-02         25          1038       93.14
23  2013-01-02         26          1008       93.14
24  2013-01-02         27          1386       93.14
25  2013-01-02         28           950       93.14
26  2013-01-02         30           708       93.14
27  2013-01-02         31          1401       93.14
28  2013-01-02         32           776       93.14
29  2013-01-02         33          1163       93.14
30  2013-01-02         34          2724       93.14
31  2013-01-02         35           786       93.14
32  2013-01-02         37          1691       93.14
33  2013-01-02         38          1987       93.14
34  2013-01-02         39          1587       93.14
35  2013-01-02         40          1178       93.14
36  2013-01-02         41           915       93.14
37  2013-01-02         43          1385       93.14
38  2013-01-02         44          4821       93.14
39  2013-01-02         45          4208       93.14
40  2013-01-02         46          4886       93.14
41  2013-01-02         47          4161       93.14
42  2013-01-02         48          3397       93.14
43  2013-01-02         49          2346       93.14
44  2013-01-02         50          3077       93.14
45  2013-01-02         51          1985       93.14
46  2013-01-02         54           998       93.14